### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by macs-overdrv**
Taking on #110 

Have not yet uncovered how to properly handle the newer `resolve_ws_with_opts` calls correctly.

This PR still builds a self-hosting cargo2nix that generates it's own Cargo.nix pins.  However, without cross compilation, dev, and other options, it's not clear that this will function correctly in enough contexts or where to start on that work.

### CODE REVIEW

**Comment by ebkalderon** [comment]
These are generally some very good changes, @macs-overdrv! Thank you so much! As mentioned in https://github.com/tenx-tech/cargo2nix/issues/110#issuecomment-659982617, `cargo` 0.46.0 was recently released and it seems to have added a `ForceAllTargets::{Yes,No}` argument which seems to alleviate our per-target feature resolution concerns we were seeing in 0.42.0 and restores the original behavior `cargo2nix` relies on. Would you mind rebasing your branch and updating to that newer version of Cargo?

If you no longer want to work on this PR, I can gladly cherry-pick your commits into a new branch and upgrade to 0.46.0 on top of it. 👍 

As an aside, would you mind perhaps fixing the email in your `.gitconfig`? It appears to be set to an empty string, which means that GitHub doesn't seem to recognize your user as a contributor to the repository. Perhaps you could use the standard `<username>@users.noreply.github.com` as your email, if you don't want to put your real address in there.

**Comment by ebkalderon** [comment]
I just tried checking out your branch, upgrading to `cargo` 0.46.0, changing the `requested_targets` argument to `&[]`, and setting `ForceAllTargets::Yes`, and I can confirm that multi-target `Cargo.nix` code generation works just fine! 👏

One behavioral change I've noticed is the increased quality and reduced repetitiveness in the generated code. For example, take a look at this:

```diff
-      ${ if hostPlatform.parsed.abi.name == "msvc" || hostPlatform.parsed.abi.name == "msvc" then "vcpkg" else null } = buildRustPackages."registry+https://github.com/rust-lang/crates.io-index".vcpkg."0.2.8" { profileName = "__noProfile"; };
+      ${ if hostPlatform.parsed.abi.name == "msvc" then "vcpkg" else null } = buildRustPackages."registry+https://github.com/rust-lang/crates.io-index".vcpkg."0.2.8" { profileName = "__noProfile"; };
```

And especially this:

```diff
-      ${ if hostPlatform.isUnix && !(hostPlatform.parsed.kernel.name == "darwin") || hostPlatform.isUnix && !(hostPlatform.parsed.kernel.name == "darwin") then "openssl_sys" else null } = rustPackages."registry+https://github.com/rust-lang/crates.io-index".openssl-sys."0.9.55" { inherit profileName; };
-      ${ if hostPlatform.isWindows || hostPlatform.isWindows then "winapi" else null } = rustPackages."registry+https://github.com/rust-lang/crates.io-index".winapi."0.3.8" { inherit profileName; };
+      ${ if hostPlatform.isUnix && !(hostPlatform.parsed.kernel.name == "darwin") then "openssl_sys" else null } = rustPackages."registry+https://github.com/rust-lang/crates.io-index".openssl-sys."0.9.55" { inherit profileName; };
+      ${ if hostPlatform.isWindows then "winapi" else null } = rustPackages."registry+https://github.com/rust-lang/crates.io-index".winapi."0.3.8" { inherit profileName; };
```

Looks much better with `cargo` 0.46.0, doesn't it?

**Comment by ebkalderon** [comment]
One issue, though, is that this branch is very outdated and lacks many fixes/changes currently in `master`. As such, I can't properly test this PR by cross-compiling `cargo2nix` itself from Darwin to `musl64` due to apparently `gcc` not being available when compiling `busybox` (?).

I'm going to try to cherry-pick and rebase your changes onto `master` in the local clone on my laptop to see if this actually works.

**Comment by ebkalderon** [comment]
Any progress here, @macs-overdrv? Anything we could assist with?

**Comment by antigravityla** [comment]
> Changing compiler versions for Cargo2nix is unnecessarilly difficult.  Whenever
a project wants to use a newer Rust feature, it shouldn't require two versions
of the Rust toolchain to present the user a shell unless Cargo2nix is incapable
of building on the project's toolchain

I kept this, but it is a drive by modification and not really integral to the PR

**Comment by antigravityla** [comment]
Seems pretty stale.  Closing in favor of #137  Contributions live on and are appreciated.

**Pull request closed without merging**
