### PR TITLE
Escape embedded TOML in profilesByName properly

### LINKED ISSUE #120: profilesByName emitting doesn't escape strings
Howdy.

I tried adding:

```
[profile.release]
lto = "fat"
```

To my Cargo.toml, but when cargo2nix generates Cargo.nix, it emits:

```
   profilesByName = {
     release = builtins.fromTOML "lto = "fat"
 ";
   };
```

I'm unclear about the redundant new-line, but the main thing here is that the quotes inside of the TOML need escaping somehow, presumably before being passed to the template.

As a workaround, I'm able to use `lto = true` instead, but there are other potentially string-valued parameters that folks might want to change, for example the `panic` parameter.

### PR DESCRIPTION
**Pull request by ebkalderon**
### Fixed

* Escape TOML output in `profilesByName` using a combination of `str::{escape_debug,replace}`.

The Tera templating code for `profilesByName` hadn't been rigorously tested, and as such, it didn't perform proper escaping of sensitive characters (e.g. `${`, `"`, and so on) before embedding the unsanitized TOML into a double-quoted Nix string in the `Cargo.nix`. This string might also contain newlines or other control characters which would need to be escaped as well.

This commit utilizes `String::escape_debug()` to perform the bulk of the escaping work, sanitizing common control characters such as `\n`, `\r`, and `\t`, and then we also replace all instances of `${` with `\${` to avoid accidental string interpolation of variables.

This bug was first introduced in #80, when we first ported `cargo2nix` to use Tera for templating.

Fixes #120. CC @philipstears

### CODE REVIEW

**Comment by ebkalderon** [comment]
An alternative approach to this problem could be to replace the TOML with a multi-line `''` string in [`templates/Cargo.nix.tera:22`](https://github.com/tenx-tech/cargo2nix/blob/b09e88570f2eaa729b2ae8b47a6a82b5fcb28de2/templates/Cargo.nix.tera#L22), which could reduce the amount of codegen-time escaping needed. I'm looking into this.

**Comment by ebkalderon** [comment]
Just had to rebase this branch after merging #119, and I needed to regenerate the `Cargo.nix` expressions and examples' version pins because they seem to have been accidentally destroyed mid-rebase while addressing changes on that PR. Would you mind reviewing again, @trha?

**Comment by philipstears** [comment]
I just had a quick test of this against my original scenario, which was the following in my `Cargo.toml`

```
[profile.release]
lto = "fat"
```

And it worked perfectly. Thanks.

**Comment by ebkalderon** [comment]
Sweet! Glad it fixed the problem, @philipstears.

**Pull request merged**
